#!/usr/bin/env bash
#checking file exists and stuff

name=school
if [ -e $name ]; then
    echo "School file exists"
else
    echo "School file does not exist"
    exit 1
fi
if [ ! -s $name ]; then
    echo "School file is empty"
else
    echo "School file is not empty"
fi
if [ -f $name ]; then
    echo "School is a regular file"
fi
